name: .NET

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v2
    
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.101'

      - name: Install dependencies
        run: |
          dotnet restore

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore

      - name: Pack
        run: |
          dotnet pack MetadataExtractor.csproj -o MetadataExtractor/

      - uses: actions/upload-artifact@v1
        with:
          name: MetadataExtractor
          path: MetadataExtractor

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/kawa0x0A/index.json" -n "github" -u kawa0x0A -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
          dotnet nuget push "./MetadataExtractor/*.nupkg" --api-key ${{secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
